name: Contributors

on:
  schedule:
    - cron: "0 12 * * 1" # Every Monday at noon
  workflow_dispatch:

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          hideName: "true" # Hide names in htmlTable
          avatarSize: 50

      - name: Modify htmlTable README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          message: "chore: update contributors"
          openDelimiter: "<!--CONTRIBUTORS_BEGIN-->"
          closeDelimiter: "<!--CONTRIBUTORS_END-->"
          body: "${{steps.contributors.outputs.htmlTable}}"
